---

- name: Install Nginx
  dnf: name=nginx state=present
  become: yes

- stat: path=/usr/share/nginx/learn.nilenso.com.access.log
  register: accesslogp
- name: Create access log file
  file: path=/usr/share/nginx/learn.nilenso.com.access.log state=touch owner=root group=root mode=0600
  when: not accesslogp.stat.exists
  become: yes

- stat: path=/usr/share/nginx/learn.nilenso.com.error.log
  register: errorlogp
- name: Create error log file
  file: path=/usr/share/nginx/learn.nilenso.com.error.log state=touch owner=root group=root mode=0600
  when: not errorlogp.stat.exists
  become: yes

- name: Configure Nginx
  template: src=nginx.conf dest=/etc/nginx/nginx.conf
  become: yes
  notify: restart nginx

- name: Configure Nginx
  template: src=default.conf dest=/etc/nginx/conf.d/default.conf
  become: yes
  notify: restart nginx

- name: Enable Nginx
  service: name=nginx enabled=yes
  become: yes

- name: Start Nginx
  service: name=nginx state=started
  become: yes
